POST http://localhost:8080/postagens/cadastrar
Content-Type: application/json


{
  "titulo": "spring web",
  "texto": "aprendendo spring relacionamento de entity",
  "comentarios": [
    {
      "codigo": 1,
      "autor": "autor da mensagem",
      "texto": "otimo"
    },
    {
      "codigo": 2,
      "autor": "autor da mensagem",
      "texto": "muito bom "
    }
  ]

}

###
POST http://localhost:8080/comentarios/cadastrar
Content-Type: application/json

{
  "autor": "autor da mensagem",
  "texto": "muito bom "
}

###
GET http://localhost:8080/comentarios/listar
Content-Type: application/json


###
DELETE http://localhost:8080/cliente
Content-Type: application/json